Rework content disposal system
KinsonDigital/Velaptor pull request #138
Opened 2022-01-24 14:24 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>

<details><summary>📄Description📄</summary>

This pull request is for preview release **_v1.0.0-preview.6_**
</details>

<h2 style="font-weight:bold" align="center">✅Development Checklist✅</h2>

<details open><summary>🌳Branching🌳</summary>
The name of the preview feature branch for this pull request has the following syntax.

Syntax: _preview/feature/&lt;issue-id&gt;-&lt;description&gt;_  
Example: _preview/feature/123-my-preview-change_
- [x] Yes
- [ ] No

The name of the branch for this pull request is merging into a preview branch with the following syntax.

Syntax: _preview/v&lt;major-number&gt;.&lt;minor-number&gt;.&lt;patch-number&gt;-preview.&lt;prev-number&gt;_  
Example: _preview/v1.2.3-preview.4_
- [x] Yes
- [ ] No

The preview feature branch for this pull request was created from a preview branch with the following syntax.

Syntax: _preview/feature/&lt;issue-id&gt;-&lt;description&gt;_  
Example: _preview/feature/123-my-preview-change_
- [x] Yes
- [ ] No
</details>

<details open><summary>🐛Bugs🐛</summary>

Contains Bug Fix(es)
- [ ] Yes
    - [ ] A ![bug-label](https://user-images.githubusercontent.com/85414302/150812958-10b202a8-84ae-45fb-b7cb-7f4fb68e0e8c.png) label has been added to the pull request.
- [x] No
</details>

<details open><summary>💣Breaking Change(s)💣</summary>

Any changes, including behavioral, that prevent a library user's application from compiling or behaving correctly.
Refer to this [link](https://docs.microsoft.com/en-us/dotnet/core/compatibility/#modifications-to-the-public-contract) for more information.
- [x] Yes
- [ ] No
</details>

<details open><summary>✨Enhancements✨</summary>

Contains enhancements that add a feature or behavior.
- [x] Yes
    - [x] An ![enhancement-label](https://user-images.githubusercontent.com/85414302/150804213-bd043c7b-54d2-4562-ad3f-69a07723a5ef.png) label has been added to the pull request.
- [ ]  No
</details>

<details open><summary>⚙️Workflow (CI/CD) Changes⚙️</summary>

These kinds of changes are only done by the project owner and maintainers.
- [ ] Yes
    - [ ] A ![workflow-label](https://user-images.githubusercontent.com/85414302/150814606-314933ca-86c7-4edb-99cb-62d2198b20d9.png) label has been added to the pull request.
- [x] No
</details>

<details open><summary>📃Documentation Updates📃</summary>

Contains changes that require documentation updates to code docs or **Velaptor** documentation.
- [x] Yes
    - [ ] I have updated the documentation accordingly.
    - [x] A ![documentation-label](https://user-images.githubusercontent.com/85414302/150810133-939e985d-2246-4c77-8c9c-815855da3664.png) label has been added to the pull request.
- [ ] No
</details>

<details open><summary>🧪Unit Testing🧪</summary>

My change requires unit tests to be written.
- [x] Yes
    - [x] I have added tests to cover my changes.
- [ ] No
</details>

<details open><summary>🧪Manual Testing🧪</summary>

I have manually tested my changes to the best of my ability.
This can be done by using the included testing application.
- [x] Yes
- [ ] No
</details>

<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [x] Pull request title matches the title of the linked issue.
- [x] The **_[add version here]_** text in the pull request description replaced with the version.
- [x] Associated issue exists and is linked to this pull request.
    - One issue per pull request.
- [x] My code follows the coding style of this project.
    - This is enforced by the *.editorconfig* files in the project and displayed as warnings.  If there is an edge case with coding style that should be ignored or changed, reach out and lets discuss it.
- [x] All tests passed locally.
    - Status checks are put in place to run unit tests every single time a change is pushed to a pull request.  This does not mean that the tests pass in both the local and CI environment.
- [x] A ![preview-label](https://user-images.githubusercontent.com/85414302/150838564-33f6044b-55f9-4dd9-8783-1d739de9d92f.png) label has been added to the pull request.

2022-01-27 20:45 UTC, CalvinWilkinson commented on Testing/VelaptorTests/OpenGL/GLWindowTests.cs
> +        public void Ctor_WithNullGlInitReactor_ThrowsException()
Refactor to below.  

```suggestion
        public void Ctor_WithNullGLInitReactor_ThrowsException()
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Caching/IDisposableItemCache.cs
> +    // TODO: Remove this
Delete entire file

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Caching/TextureCache.cs
> +        /// <param name="disposeTexturesReactor">Sends a notifications to dispose of textures.</param>
Refactor to below

```suggestion
        /// <param name="disposeTexturesReactor">Sends push notifications to dispose of textures.</param>
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Factories/SoundFactory.cs
> +        /// <param name="shutDownReactor">Sends push notifications that the application is shutting down.</param>
Refactor to below

```suggestion
        /// <param name="shutDownReactor">Sends a push notification that the application is shutting down.</param>
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Fonts/IFont.cs
> +        /// Gets a value indicating whether or not font is a default font.
Refactor below

```suggestion
        /// Gets a value indicating whether or not the font is a default font.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Texture.cs
> +        /// Disposes of the texture if this textures <see cref="Id"/> matches the given <paramref name="data"/>.
Refactor to below

```suggestion
        /// Disposes of the texture if this textures <see cref="Id"/> matches the texture ID in the given <paramref name="data"/>.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Content/Texture.cs
> +        /// <param name="data">The ID of the texture to dispose.</param>
Refactor to below

```suggestion
        /// <param name="data">The data of the texture to dispose.</param>
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/IoC.cs
> +using Velaptor.Observables.ObservableData;
Move this using statement to the rest of the using statements below

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/DisposeSoundsReactor.cs
> +    /// Creates an observable to send push notifications to signal that an object needs to be disposed.
Refactor to below

```suggestion
    /// Creates an observable to send push notifications to signal that a sound needs to be disposed.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/DisposeSoundsReactor.cs
> +        /// Sends a push notification to signal that an object needs to be disposed.
Refactor to below

```suggestion
        /// Sends a push notification to dispose of a sound.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/DisposeTexturesReactor.cs
> +    /// Creates an observable to send push notifications to signal that an object needs to be disposed.
Refactor to below

```suggestion
    /// Creates an observable to send push notifications to signal that a texture needs to be disposed.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/DisposeTexturesReactor.cs
> +        /// Sends a push notification to signal that an object needs to be disposed.
Refactor to below

```suggestion
        /// Sends a push notification to dispose of a texture.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/ObservableData/GLInitData.cs
> +    /// Holds da ta for the <see cref="IReactor{T}"/>.
Fix spelling mistake

```suggestion
    /// Holds data for the <see cref="IReactor{T}"/>.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/ObservableData/RemoveBatchItemData.cs
> +    /// Holds da ta for the <see cref="IReactor{T}"/>.
Fix spelling mistake

```suggestion
    /// Holds data for the <see cref="IReactor{T}"/>.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/ObservableData/ShutDownData.cs
> +    /// Holds da ta for the <see cref="IReactor{T}"/>.
Fix spelling mistake

```suggestion
    /// Holds data for the <see cref="IReactor{T}"/>.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLContextReactor.cs
>      /// Creates an observable to send push notifications of OpenGL events.
Refactor to below.

```suggestion
    ///  Creates an observable to send push notification that the <c>OpenGL</c> context has been created.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLContextReactor.cs
>          /// <param name="data">The data to send with the notification.</param>
Add a summary section that the reactor(observable) auto unsubscribes itself after processing all of the push notifications.

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLContextReactor.cs
> +            for (var i = Observers.Count - 1; i >= 0; i--)
Add code after the for loop to unsubscribe all of the observers.  This will make the Reactor auto unsubscribing

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLInitReactor.cs
> +    /// Creates an observable to send push notifications of OpenGL events.
Refactor summary code doc

```suggestion
    /// Creates an observable to send push notification that OpenGL is initialized.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLInitReactor.cs
> +        /// <param name="data">The data to send with the notification.</param>
Add summary section explaining that this Reactor unsubscribes all observers after processing push notifications if the new default param of `bool unsubscribeAfterProcessing` is true.

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/OpenGLInitReactor.cs
> +        public override void PushNotification(GLInitData data)
Add new parameter called `bool unsubscribeAfterProcessing` with a default value of false

Do this for all `Reactor` types in code base

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/Observables/RemoveBatchItemReactor.cs
> +        /// Sends a push notification to remove a batch item from a batch service.
Refactor code doc

```suggestion
        /// Sends a push notification to remove a batch item.
```

2022-01-27 20:45 UTC, CalvinWilkinson commented on Velaptor/OpenGL/GLWindow.cs
> +        /// <param name="glInitReactor">Provides push notifications to OpenGL related events.</param>
Refactor doc

```suggestion
        /// <param name="glInitReactor">Provides push notifications that OpenGL has been initialized.</param>
```

2022-01-27 22:01 UTC, kselena requested changes

2022-01-28 10:54 UTC, CalvinWilkinson commented on Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
> +        public void ShutDownNotification_WhenReceived_DisposesOfTextures()
This is a special case where I am checking for behavior by triggering an event internal to the class.  I can't test it by executing a public method or property.  This is why you dont see a method name called `ShutDownNotification()`

2022-01-31 13:41 UTC, kselena approved these changes

2022-01-31 14:31 UTC, merged