Improve button control by using primitive rectangles
KinsonDigital/Velaptor pull request #211
Opened 2022-02-26 12:52 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>

<h2 style="font-weight:bold" align="center">✅Development Checklist✅</h2>

<details open><summary>🌳Branching🌳</summary>

Does the name of the head(source) branch for this pull request have the correct **_preview feature branch_** syntax?

Syntax: _preview/feature/&lt;issue-id&gt;-&lt;description&gt;_  
Example: _preview/feature/123-my-preview-change_
- [ ] Yes
- [ ] No

Does the name of the base(target) branch for this pull request have the correct **_preview branch_** syntax?

Syntax: _preview/v&lt;major-number&gt;.&lt;minor-number&gt;.&lt;patch-number&gt;-preview.&lt;prev-number&gt;_  
Example: _preview/v1.2.3-preview.4_
- [ ] Yes
- [ ] No

Is the head(source) branch for this pull request created from a branch with the correct **_preview branch_** syntax?

Syntax: _preview/v&lt;major-number&gt;.&lt;minor-number&gt;.&lt;patch-number&gt;-preview.&lt;prev-number&gt;_  
Example: _preview/v1.2.3-preview.4_
- [ ] Yes
- [ ] No
</details>

<details open><summary>🐛Bugs🐛</summary>

Contains Bug Fix(es)
- [ ] Yes
  - [ ] A ![bug-label](https://user-images.githubusercontent.com/85414302/150812958-10b202a8-84ae-45fb-b7cb-7f4fb68e0e8c.png) label has been added to the pull request.
- [ ] No
</details>

<details open><summary>💣Breaking Change(s)💣</summary>

Contains [breaking change(s)](https://docs.microsoft.com/en-us/dotnet/core/compatibility/#modifications-to-the-public-contract)
- [ ] Yes
  - [ ] A ![breaking-change-label](https://user-images.githubusercontent.com/85414302/154378943-8e684157-2138-404d-ba19-b9d76061c12e.png) label has been added to the pull request.
- [ ] No
</details>

<details open><summary>✨Enhancements✨</summary>

Contains enhancement(s) that add a feature or behavior.
- [ ] Yes
  - [ ] An ![enhancement-label](https://user-images.githubusercontent.com/85414302/150804213-bd043c7b-54d2-4562-ad3f-69a07723a5ef.png) label has been added to the pull request.
- [ ]  No
</details>

<details open><summary>⚙️Workflow (CI/CD) Changes⚙️</summary>

Contains changes to workflow files. These changes can only be done by the project maintainers.
- [ ] Yes
  - [ ] A ![workflow-label](https://user-images.githubusercontent.com/85414302/150814606-314933ca-86c7-4edb-99cb-62d2198b20d9.png) label has been added to the pull request.
- [ ] No
</details>

<details open><summary>📃Documentation Updates📃</summary>

Contains changes that require updates to existing **_code_** and/or **_Velaptor product_** documentation.
- [ ] Yes
  - [ ] I have updated the documentation accordingly.
    - Choose the type of documentation.
    - [ ] Code Documentation
      - [ ] A ![documentation-code-label](https://user-images.githubusercontent.com/85414302/154672489-8079ed03-b8ff-41ff-9864-1e2ae55300cc.png) label has been added to the pull request.
    - [ ] Product Documentation
      - [ ] A ![documentation-product-label](https://user-images.githubusercontent.com/85414302/154672508-5ac50eb7-67f8-4cdf-92b9-fe5fcbd93b14.png) label has been added to the pull request.
- [ ] No
</details>

<details open><summary>🧪Unit Testing🧪</summary>

My change requires unit tests to be written.
- [ ] Yes
- [ ] No
</details>

<details open><summary>🧪Manual Testing🧪</summary>

I have manually tested my changes using the project named **_VelaptorTesting_**.
- [ ] Yes
- [ ] No
</details>

<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [ ] Pull request title matches the title of the linked issue.
- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.
- [ ] My code follows the coding style of this project.
  - The style is enforced by the *.editorconfig* files in the project and displayed as warnings.  If there is an edge case with a coding style that should be ignored or changed, reach out, and let's discuss it.
- [ ] A ![preview-label](https://user-images.githubusercontent.com/85414302/150838564-33f6044b-55f9-4dd9-8783-1d739de9d92f.png) label has been added to the pull request.
- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vise-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - This does not mean that the tests pass in both the local and CI environment.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-03-01 21:14 UTC, CalvinWilkinson reviewed
Requesting Changes

2022-03-04 15:49 UTC, CalvinWilkinson reviewed
Changes requested

2022-03-04 15:49 UTC, CalvinWilkinson commented on Testing/VelaptorTesting/Program.cs
> +        public static void Main(string[] args)
Implement additional functionality.

- [ ] Implement a message that the application has started.
- [ ] Add some help text explaining the commands.
- [ ] Add another command to show help

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The source rectangle inside of the texture to render.
Refactor to:

```suggestion
        /// The source rectangle inside of the font atlas texture to render.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The destination rectangular area of where to render the texture on the screen.
Refactor to:

```suggestion
        /// The destination rectangular area of where to render the font atlas texture on the screen.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +    internal struct FontBatchItem : IEquatable<FontBatchItem>
Refactor struct name to `FontGlyphBatchItem`

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The size of the texture to be rendered.
Refactor to:

```suggestion
        /// The size of the glyph texture to be rendered.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The angle in degrees of the texture.
Refactor to:

```suggestion
        /// The angle in degrees of the glyph texture.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The color to apply to the entire texture.
Refactor to:

```suggestion
        /// The color to apply to the entire glyph texture.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The type of effects to apply to the texture when rendering.
Refactor to:

```suggestion
        /// The type of effects to apply to the glyph texture when rendering.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/OpenGL/FontBatchItem.cs
> +        /// The ID of the texture.
Refactor to:

```suggestion
        /// The ID of the font atlas texture.
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/Services/FontBatchService.cs
> +    /// Manages the process of batching up the rendering of text.
Refactor to:

```suggestion
    /// Manages the process of batching up glyphs to be rendered..
```

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/Services/FontBatchService.cs
> +    internal class FontBatchService : IBatchManagerService<FontBatchItem>
Refactor name to `FontGlyphBatchService`

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/Services/FontBatchService.cs
> +        /// <remarks>
Refactor remarks section to only include:

`The batch is ready when the total amount of items to be rendered is equal to the <see cref="BatchSize"/>.`

2022-03-04 15:49 UTC, CalvinWilkinson commented on Velaptor/Services/FontBatchService.cs
> +        public void Add(FontBatchItem rect)
Refactor param name `rect` to `item`

2022-03-04 17:19 UTC, CalvinWilkinson reviewed
PR Approved

2022-03-04 20:00 UTC, kselena requested changes

2022-03-04 21:53 UTC, CalvinWilkinson commented on Testing/VelaptorTesting/Scenes/TestRenderTextScene.cs
>          private const string MultiLineText = "Change me using\nthe buttons to the left.";
This is intended.  This is not a miss-spelling.

Anytime you see the value `\n` or `\t` in a string literal, this is an escape sequence to send the text after the escape sequence to next line, or tab before the space.

`\n` means new line
`\t` means a tab

2022-03-05 10:04 UTC, CalvinWilkinson commented on Velaptor/Content/Fonts/IFont.cs
> +        ///     the <paramref name="textPos"/>.  The position is relative to the top left corner of the character.
This is correct and does not need to be changed.

The bounds contains a position and that position is relative to the top left corner of the glyph/character itself, not the center for example.

![image](https://user-images.githubusercontent.com/85414302/156878621-865874c7-97f4-4735-ae36-d262b737f2e1.png)

2022-03-05 10:10 UTC, CalvinWilkinson commented on Velaptor/OpenGL/Buffers/RectGPUBuffer.cs
> +            // TODO: This needs to be unit tested
Yes.  Converted to an issue

2022-03-05 10:10 UTC, CalvinWilkinson commented on Velaptor/OpenGL/Buffers/RectGPUBuffer.cs
> +            // TODO: This needs to be unit tested
Yes.  Converted to an issue

2022-03-05 10:18 UTC, CalvinWilkinson commented on Velaptor/UI/TextBox.cs
>              // TODO: Setup textbox border rect
This entire control is subject to change and cannot be used by the user.

You can see this by looking at line 21.

``` cs
internal class TextBox : ControlBase
```

The keyword `internal` means that it is only accessible by the code in this library.  Any code outside of this library cannot use it and does not have access.  For example, the user using this library would not be able to use this entire class.

They would not be able to do the code below.

``` cs
var myTextBox = new TextBox();
```

2022-03-05 10:44 UTC, merged