Update Branching Documentation
KinsonDigital/Velaptor pull request #288
Opened 2022-07-10 21:22 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">✅Code Review Checklist✅</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the projects [branching documentation](../../Documentation/Branching.md).

- [ ] Pull request title matches the title of the associated issue.

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out and let's discuss it.

- [ ] A ![preview-label](https://user-images.githubusercontent.com/85414302/150838564-33f6044b-55f9-4dd9-8783-1d739de9d92f.png) label has been added to the pull request.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - This does not mean that the tests pass in both the local and CI environment.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-07-10 22:30 UTC, CalvinWilkinson commented
@kselena Please highly scrutinize the changes for this PR.  This is the branching documentation and I want to make sure that it makes sense.

Thanks!!

2022-07-11 14:37 UTC, kselena requested changes

2022-07-12 11:30 UTC, kselena commented on Documentation/Branching.md
> +This branch is where urgent bug fixes or changes will be performed.  This should be carefully reviewed and only done when something with the software is considered **broken** and/or **unusable**.  Ch
I  would italicize Note, but I like it.  I make a couple of small changes to the last two sentences.

2022-07-12 11:31 UTC, kselena requested changes
I changed VS Code by parsing together the last two sentences.  I would also make "Note" italicized.  Other than that, it's good.

2022-07-12 12:46 UTC, kselena approved these changes

2022-07-12 12:47 UTC, KinsonDigitalAdmin approved these changes

2022-07-12 12:48 UTC, merged