🚀Preview Release
KinsonDigital/Velaptor pull request #387
Opened 2022-10-17 10:27 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Release Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [x] The **_head(source)_** branch for this pull request is a **_preview_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

- [x] The **_base(target)_** branch for this pull request is a **_release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: release/v<major>.<minor>.<patch>
      Example: release/v1.2.3
      ```
    </details>

- [x] The **_head(source)_** branch for this pull request is created from a **_release_** branch with the correct naming syntax in the following example.
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: release/v<major>.<minor>.<patch>
    Example: release/v1.2.3
    ```
  </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [x] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [x] Pull request title is set to _**🚀Preview Release**_.

- [x] A `🚀Preview Release` label has been added to this pull request. 

- [x] Project assigned matches the project of the associated issue.

- [x] Milestone assigned matches the milestone of the associated issue.

- [x] A QA issue has been created and manual QA testing has been performed for the changes being released _(if applicable)_.

2022-10-17 15:33 UTC, kselena requested changes

2022-10-17 15:33 UTC, kselena commented on Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.10.md
> +1. [#310](https://github.com/KinsonDigital/Velaptor/issues/310) - Made simple grammar change to the project's readme document.
grammar
```suggestion
1. [#310](https://github.com/KinsonDigital/Velaptor/issues/310) - Made simple grammar changes to the project's readme document.
```

2022-10-17 22:31 UTC, KinsonDigitalAdmin approved these changes, later dismissed

2022-10-18 09:50 UTC, kselena approved these changes, later dismissed

2022-10-18 12:29 UTC, KinsonDigitalAdmin approved these changes

2022-10-18 12:29 UTC, merged