🚧Implement Carbonate library
KinsonDigital/Velaptor pull request #478
Opened 2022-12-20 08:00 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2022-12-21 15:59 UTC, CalvinWilkinson commented
Put https://github.com/KinsonDigital/Velaptor/labels/on%20hold

**Reason:** refer to linked issue [comment](https://github.com/KinsonDigital/Velaptor/issues/473#issuecomment-1361557296) for more information.

2022-12-26 15:48 UTC, KinsonDigitalAdmin requested changes

2022-12-26 15:48 UTC, KinsonDigitalAdmin commented on Velaptor/ReactableData/BatchSizeData.cs
> +/// Holds data for the <see cref="Reactable"/> reactable.
Refactor to:

```suggestion
/// Holds data for the the size of the batch.
```

2022-12-26 15:48 UTC, KinsonDigitalAdmin commented on Velaptor/Content/Caching/SoundCache.cs
> +    [ExcludeFromCodeCoverage(Justification = "De-constructors cannot be unit tested.")]
Add justifications to all of the `[ExcludeFromCodeCoverage]` attributes.

2022-12-26 15:48 UTC, KinsonDigitalAdmin commented on Velaptor/NotificationIds.cs
> +    public static Guid ShutDownId { get; } = new ("17b9fd1c-67ef-4f36-8973-45e32b0ee85b");
Give these property names better past-tense type event names.

Example: `GLInitId `should be changed to `GLInitializedId`

2022-12-26 16:02 UTC, kselena requested changes

2022-12-26 16:02 UTC, kselena commented on Velaptor/ReactableData/KeyboardKeyStateData.cs
> +    /// Gets or sets a value indicating whether the current <see cref="Key"/> is in the down position.
Grammar
```suggestion
    /// Gets or sets a value indicating whether or not the current <see cref="Key"/> is in the down position.
```

2022-12-26 17:55 UTC, KinsonDigitalAdmin approved these changes

2022-12-26 17:56 UTC, kselena approved these changes

2022-12-26 17:59 UTC, merged