🚧Improve render system
KinsonDigital/Velaptor pull request #483
Opened 2022-12-27 10:35 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2023-01-11 11:17 UTC, kselena requested changes

2023-01-11 11:17 UTC, kselena commented on Testing/VelaptorTests/OpenGL/Buffers/FontGPUBufferTests.cs
> +                    // RETURN NULL TO SIMPLY IGNORE THIS EVENT ID
Refactor to remove simply
```suggestion
                    // RETURN NULL TO IGNORE THIS EVENT ID
```

2023-01-11 11:17 UTC, kselena commented on Testing/VelaptorTests/OpenGL/Buffers/RectGPUBufferTests.cs
> +                    // RETURN NULL TO SIMPLY IGNORE THIS EVENT ID
Refactor to remove simply
```suggestion
                    // RETURN NULL TO IGNORE THIS EVENT ID
```

2023-01-11 11:17 UTC, kselena commented on Velaptor/Graphics/IRenderer.cs
>      /// Gets or sets the color that the back buffer will be cleared to.
Grammar
```suggestion
    /// Gets or sets the color where the back buffer will be cleared.
```

2023-01-11 11:17 UTC, kselena commented on Velaptor/OpenGL/Buffers/TextureGPUBuffer.cs
>          // Set up the corners of the sub texture to render
Grammar
```suggestion
        // Sets the corners of the sub texture to render
```

2023-01-11 11:17 UTC, kselena commented on Velaptor/OpenGL/GLWindow.cs
>          // Update the viewport so it is the same size as the window
Grammar
```suggestion
        // Updates the viewport so it is the same size as the window
```

2023-01-11 11:17 UTC, kselena commented on Velaptor/OpenGL/TextureBatchItem.cs
>      /// <param name="tintColor">The color to apply to an entire texture.</param>
Wordy
```suggestion
    /// <param name="tintColor">The color to apply to a texture.</param>
```

2023-01-11 11:17 UTC, kselena commented on Velaptor/ReactableData/ViewPortSizeData.cs
> +/// Holds the size of the view port.
Refactor - should be one word
```suggestion
/// Holds the size of the viewport.
```

2023-01-11 15:44 UTC, KinsonDigitalAdmin submitted a review, later dismissed

2023-01-12 14:39 UTC, KinsonDigitalAdmin approved these changes

2023-01-12 14:42 UTC, kselena approved these changes

2023-01-12 14:43 UTC, merged