🚧Move and improve scene system to Velaptor
KinsonDigital/Velaptor pull request #514
Opened 2023-02-06 17:56 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](../../Documentation/Branching.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2023-02-06 23:21 UTC, CalvinWilkinson commented
> **Warning** Added a https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> This was due to renaming the `IWindowActions` interface to `IWindowEvents`

2023-02-06 23:32 UTC, CalvinWilkinson commented
> **Warning** Added a https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> This was due to deleting the `IWindowProps` interface.  It was combined into the `IWindow` interface.

2023-02-08 00:17 UTC, CalvinWilkinson commented
> **Note** Increased https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%8F%8E%EF%B8%8Fperformance by converting the `FrameTime` struct to a `readonly record` struct.

2023-02-08 11:45 UTC, kselena requested changes

2023-02-08 11:45 UTC, kselena commented on Velaptor/Factories/IReactableFactory.cs
>      /// Creates a view port reactable.
Spelling.  Refactor to make viewport one word.
```suggestion
    /// Creates a viewport reactable.
```

2023-02-08 11:45 UTC, kselena commented on Velaptor/Scene/ISceneManager.cs
> +    ///     <c>true</c> if a scened exists with the given id.
Spelling (scene and ID)
```suggestion
    ///     <c>true</c> if a scene exists with the given ID.
```

2023-02-08 11:45 UTC, kselena commented on Velaptor/Scene/SceneManager.cs
> +            // TODO: Create custom exception for this
Do you still need this TODO?
```suggestion
            // TODO: Create custom exception for this
```

2023-02-08 11:45 UTC, kselena commented on Velaptor/UI/IWindow.cs
> +    /// Gets or sets a value indicating whether or not the buffers should]
Grammar (remove bracket)
```suggestion
    /// Gets or sets a value indicating whether or not the buffers should
```

2023-02-08 13:43 UTC, CalvinWilkinson commented on Velaptor/Scene/SceneManager.cs
> +            // TODO: Create custom exception for this
New exception created and test updated

2023-02-08 13:53 UTC, KinsonDigitalAdmin requested changes

2023-02-08 13:53 UTC, KinsonDigitalAdmin commented on Velaptor/Scene/ISceneManager.cs
> +
remove extra line

2023-02-08 14:24 UTC, KinsonDigitalAdmin approved these changes, later dismissed

2023-02-08 15:53 UTC, kselena requested changes

2023-02-08 15:53 UTC, kselena commented on Velaptor/Scene/ISceneManager.cs
>      ///     the all other scenes will bet set to inactive.
Grammar
```suggestion
    ///     all other scenes will bet set to inactive.
```

2023-02-08 15:56 UTC, KinsonDigitalAdmin approved these changes

2023-02-08 15:57 UTC, kselena approved these changes

2023-02-08 16:05 UTC, merged