🚧Create image loader
KinsonDigital/Velaptor pull request #588
Opened 2023-04-07 15:08 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Preview Feature Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_preview feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/feature/<issue-num>-<description>
      Example: preview/feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_preview release_** branch, with the correct naming syntax, in the following example:
  <details closed><summary>Example</summary>

    ``` xml
    Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
    Example: preview/v1.2.3-preview.4
    ```
  </details>

- [ ] The **_base(target)_** branch for this pull request is a **_preview release_** branch, with the correct naming syntax, in the following example:
  - A **_base(target)_** branch is the branch that the **_head(source)_** branch is merging into.

    <details closed><summary>Example</summary>

      ``` xml
      Syntax: preview/v<major>.<minor>.<patch>-preview.<prev-num>
      Example: preview/v1.2.3-preview.4
      ```
    </details>

💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/BranchingFullGitFlow.md).

- [ ] Associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] Pull request title matches the title of the associated issue.

- [ ] A `preview` label has been added to the pull request.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] Project assigned matches the project of the associated issue.

- [ ] Milestone assigned matches the milestone of the associated issue.

- [ ] My code follows the coding style of this project.
  - The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's discuss it.

- [ ] I have manually tested my code changes to the best of my ability.

- [ ] All tests passed locally.
  - This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
  - Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
  - Status checks run for this pull request when merging into the **_preview/v\*.\*.\*-preview.\*_** branch.  These status checks run every time a change is pushed to the pull request.  These checks validate version syntax, tagging, builds, unit tests, and more.

2023-04-07 17:44 UTC, CalvinWilkinson commented
> **Warning** Added https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes.
The public fields for the `ImageData` struct have been converted into `readonly` properties.

2023-04-07 17:47 UTC, CalvinWilkinson commented
> **Warning** Added https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> The `Texture` constructor signature has been changed from `public Texture(string, string)` to `public Texture(string, string, ImageData)`.

An additional constructor has been added though to allow the use of the `ImageData` struct.

2023-04-08 06:55 UTC, KinsonDigitalAdmin requested changes

2023-04-08 06:55 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/Content/Caching/TextureCacheTests.cs
> +        this.mockPath.Setup(m => m.IsPathRooted(It.IsAny<string>())).Returns(true);
These lines are duplicated in several locations in the file.  Remove one of the duplicates.

2023-04-08 06:58 UTC, KinsonDigitalAdmin approved these changes, later dismissed

2023-04-08 13:09 UTC, CalvinWilkinson commented
> **Note** Added a https://github.com/KinsonDigital/Velaptor/labels/%E2%9C%A8new%20feature to `ImageData`
> Added 2 methods with the name `FlipHorizontally()` and `FlipVertically()` to make it easy to flip images.
> Also added 2 properties with the names `IsFlippedHorizontally` and 'IsFlippedVertically` to make it easy to know if the image is flipped in either direction compared to its original state when loaded.

2023-04-10 07:26 UTC, KinsonDigitalAdmin approved these changes

2023-04-10 07:26 UTC, merged