Start work for issue #237
KinsonDigital/Velaptor pull request #761
Opened 2023-10-12 19:56 UTC by AndreBonda

2023-10-15 13:20 UTC, KinsonDigitalAdmin requested changes

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
> +        var invalidValue = 123;
Please convert this to a `const`.

```suggestion
        const invalidValue = 123;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/Input/MouseTests.cs
> +        var invalidMouseButton = 1234;
Please convert to a `const`

```suggestion
        const invalidMouseButton = 1234;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
>          act.Should().Throw<ArgumentOutOfRangeException>().WithMessage(exceptionMsg);
Please fix compile error.

I am getting a build error because the argument being sent into the `WithMessage()` method should be named `expected`.
The variable `exceptionMsg` does not exist.

 ```suggestion
        act.Should().Throw<ArgumentOutOfRangeException>().WithMessage(expected);
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
>      public void LabelBuffer_WithInvalidBufferType_ThrowsException()
Please adjust the code being tested to allow the test to pass.
This test is failing because the wrong exception is being used in the code being tested.
The exception being used is `ArgumentOutOfRangeException` but should be `InvalidEnumArgumentException`.

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/OpenGL/GLWindowTests.cs
> +        var invalidValue = 1234;
Please refactor this to a constant

```suggestion
        const invalidValue = 1234;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/OpenGL/GLWindowTests.cs
> +        var invalidValue = 1234;
Please refactor this to a constant

```suggestion
        const invalidValue = 1234;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/OpenGL/GLWindowTests.cs
> +        var invalidValue = 1234;
Please change to a constant

```suggestion
        const invalidValue = 1234;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/OpenGL/GLWindowTests.cs
> +        var invalidValue = 1234;
Please refactor to a constant

```suggestion
        const invalidValue = 1234;
```

2023-10-15 13:20 UTC, KinsonDigitalAdmin commented on Velaptor/Input/Mouse.cs
> +    ///     Occurs if the <see cref="MouseStateData.Button"/> is an invalid value.
Please refactor this XAML doc to show `MouseStateData` as well as `Button`.

```suggestion
    ///     Occurs if the <see cref="MouseStateData"/>.<see cref="MouseStateData.Button"/> is an invalid value.
```

2023-10-16 06:18 UTC, AndreBonda commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
>          act.Should().Throw<ArgumentOutOfRangeException>().WithMessage(exceptionMsg);
I think this is caused by a wrong merge.

2023-10-16 06:18 UTC, AndreBonda commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
>      public void LabelBuffer_WithInvalidBufferType_ThrowsException()
I think this is caused by a wrong merge.

2023-10-22 14:06 UTC, KinsonDigitalAdmin approved these changes

2023-10-22 14:07 UTC, KinsonDigitalAdmin commented on Testing/VelaptorTests/NativeInterop/OpenGL/OpenGLServiceTests.cs
>          act.Should().Throw<ArgumentOutOfRangeException>().WithMessage(exceptionMsg);
You are correct.  This was due to the update to this PR from a previous merge into the base branch.  Good catch.

2023-10-22 14:08 UTC, merged