Feature/803 refactor glyphmetrics to readonly record
KinsonDigital/Velaptor pull request #820
Opened 2023-11-24 17:46 UTC by map-b

2023-11-26 11:12 UTC, CalvinWilkinson requested changes

2023-11-26 11:12 UTC, CalvinWilkinson commented on Testing/VelaptorTests/Graphics/GlyphMetricsTests.cs
Please delete this file.

> **Note**
> The tests are also failing but do not need to be fixed due to deleting the file.

**Reason:**
The things that are tested now come built into the struct because it is now a record struct.  So that means we are testing dotnet implementations which of course is not necessary.

2023-11-26 19:11 UTC, map-b commented on Testing/VelaptorTests/Graphics/GlyphMetricsTests.cs
Done, I just wanted to double check the changes were correct. 😄

2023-11-27 08:48 UTC, CalvinWilkinson approved these changes

2023-11-27 08:48 UTC, CalvinWilkinson commented
@map-b Approved and merged!!

Awesome work map and I appreciate the collaboration.  😀

2023-11-27 08:49 UTC, merged

2024-01-01 17:40 UTC, CalvinWilkinson commented
> [!WARNING]
> Introduced the following https://github.com/KinsonDigital/Velaptor/labels/%F0%9F%A7%A8breaking%20changes
> 1. Refactored the `GlyphMetrics` struct to a `readonly record` struct.